name: stickybotweb
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.0-134.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  url_launcher: ^6.0.18
  flutter_svg: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/instagram.svg
    - assets/twitter.svg
    - assets/tiktok.svg
    - assets/youtube.svg

  # fonts:
